extends Node

# mech ambulation
signal MECH_FORWARD_SIGNAL_ON
signal MECH_FORWARD_SIGNAL_OFF
signal MECH_BACKWARD_SIGNAL_ON
signal MECH_BACKWARD_SIGNAL_OFF
signal MECH_LEFT_STRAFE_SIGNAL_ON
signal MECH_LEFT_STRAFE_SIGNAL_OFF
signal MECH_RIGHT_STRAFE_SIGNAL_ON
signal MECH_RIGHT_STRAFE_SIGNAL_OFF
signal MECH_LEFT_ROTATE_SIGNAL_ON
signal MECH_LEFT_ROTATE_SIGNAL_OFF
signal MECH_RIGHT_ROTATE_SIGNAL_ON
signal MECH_RIGHT_ROTATE_SIGNAL_OFF

# sonar
signal SONAR_WALL_PINGED(position: Vector3)

# plugs
signal PLUG_PICKED(origin: Plug)
signal PLUG_DROPPED
signal PLUG_HOVERED(hovered: Plug)
signal PLUG_UNHOVERED(unhovered: Plug)
